### ISSUE TITLE
Не правильное отображение SayText сообщения

### ISSUE THREAD

**Issue by THE-Swank** [FWGS/cs16-client#198]
Если клинту послать SayText и в первом параметре указать его же ID то вместо сообщения просто отобразится белым текстом двоеточие.

**Comment by a1batross** [comment]
Кроме двоеточего ничего не будет? 

Показывай какую мессагу шлёшь. Всю.

**Comment by THE-Swank** [comment]
message_begin(MSG_ONE, g_msg_say_text, {0,0,0}, player)
        write_byte(player)
        write_string(message)
        message_end()
Так шлю, везде в модах так же само шлется.

**Comment by THE-Swank** [comment]
Нет, кроме белого двоеточия нечего.

**Comment by a1batross** [comment]
@THE-Swank Плохо шлёшь.
```
	char szBuf[3][64];
	int client_index = reader.ReadByte();		// the client who spoke the message
	strncpy( szBuf[0], reader.ReadString(), sizeof(szBuf[0]));
	strncpy( szBuf[1], reader.ReadString(), sizeof(szBuf[1]));
	strncpy( szBuf[2], reader.ReadString(), sizeof(szBuf[2]));
```

**Comment by a1batross** [comment]
Not a bug.
