### ISSUE TITLE
ZBot bots current status.

### ISSUE THREAD

**Issue by Jan200101** [FWGS/cs16-client#200]
Currently ZBot is illegal because of the way it imports bots.
It imports the Condition Zero dll and replaces a few paramaters used for Bots.

> There is an illegal mod though, called "Zbots". It's not illegal because they're bots, or that it mods the game, it's illegal because they're Condition Zero bots ported to CS 1.6. Everyone uses these, but the bots have terrible AI in CS 1.6 maps.

I would suggest removing it or replacing it with Podbot

**Comment by a1batross** [comment]
There is YaPB available. 

Just uncheck ZBot in launcher.
