### ISSUE TITLE
Иконка Xash3D в CS16Client на некоторых устройствах

### ISSUE THREAD

**Issue by VladAndroidGamer** [FWGS/cs16-client#205]
Hi, dear "cs16-client" player. :)

Since developers are too busy, we don't have too much time to work with each bug of each user.

So before you will press *Submit* button, make sure you have checked all the paragraphs below:
- [ ] I looked through the Issues section of this repository.
- [ ] I looked through the Issues section of https://github.com/FWGS/xash3d repository.
- [ ] I installed fresh game data from my Steam account.
- [ ] I installed latest versions of cs16-client and Xash3D port. (look here: https://github.com/FWGS/cs16-client/releases/latest and https://github.com/FWGS/xash3d-android-project/releases/latest)
- [ ] I looked through the Issues section of https://github.com/FWGS/xash3d-android-project repository.

You are still here? Great! This means that you have a new bug. But this is not the end. For our mutual understanding, we require some data from you:
- [ ] Short description of your problem.
- [ ] Information about your device: RAM size, CPU, GPU and OS. 
- [ ] engine.log. You can find that in your "xash" folder. If there is not log, re-run game with "-log" command line parameter. 
- [ ] adb logcat. Isn't necessary, but it will be very nice, if you can post this. You can ask Google for "How to get the "logcat" data", if you don't know what is it.

**Comment by a1batross** [comment]
Для кого я составлял руководство о том, как надо составлять баги?

2016-09-28 19:05 GMT+03:00 VladAndroidGamer <notifications@github.com>:
