### ISSUE TITLE
Credits list

### ISSUE THREAD

**Issue by RomkaZVO** [FWGS/cs16-client#207]
A1batross, я тебе тут список перепеисал, убарл тех, кто вообще молчал:

_____________
DEVELOPERS
_____________
a1batross
mittorn
nicknekit
jeefo
Solexid
__________________
TOUCH&GFX
__________________
ahsim
SergioPoverony
_____________
TESTERS
_____________
Romka_ZVO
Velaron
Zu1iN~Mage
Maks56873
THE-Swank
BloodyLuxor
AndroUser Bbltashit
Athiend
*KinG*
vlad[54rus]
Messi
CSPlayer
MeL0maN
Rediska_Morkovka
Mr.Lightning Bolt
Kirpich
WolfReiser
IcE
picos
Cosmo
LordAlfaruh

**Comment by a1batross** [comment]
Убирать уже не буду, я попросту не помню, а добавить добавлю.
13.10.2016 10:50 пользователь "Роман" <notifications@github.com> написал:
