### ISSUE TITLE
cl_weather не влияет на кол снега при присуцтвии env_snow на мапе

### ISSUE THREAD

**Issue by THE-Swank** [FWGS/cs16-client#210]
Что при cl_weather 1, что при cl_weather 3 кол. идущего снега одинаково.

**Comment by vlad54rus** [comment]
Помимо снега, данная комадна должна влиять и на дождь на de_aztec, но тоже ничего не меняет.

**Comment by a1batross** [comment]
Даже и не знал, что оно должно влиять. Неудивительно, что не работает.
