### ISSUE TITLE
Команда bot_quota

### ISSUE THREAD

**Issue by porloc** [FWGS/cs16-client#214]
Дорогие разработчики, добавьте пожалуйста команду bot_quota для автоматического создания ботов в нужном количестве. Как в zbot для CS1.6 для ПК. А то неудобно 10 раз прописывать команду bot_add

**Comment by nekonomicon** [comment]
Это шутка такая?) bot_quota работает :)
Да и бот меню есть.

**Comment by RomkaZVO** [comment]
Аж смешно стало, есть бот квота, а ещё удобнее юзать ботменю
