### ISSUE TITLE
Add buy button

### ISSUE THREAD

**Issue by ThatDAMNGuy** [FWGS/cs16-client#216]
Hi, dear "cs16-client" player. :)

Since developers are too busy, we don't have too much time to work with each bug of each user.
There's no buy weapons button in-game
So before you will press *Submit* button, make sure you have checked all the paragraphs below:
- [x] I installed latest versions of cs16-client and Xash3D port. (look here: https://github.com/FWGS/cs16-client/releases/latest and https://github.com/FWGS/xash3d-android-project/releases/latest)
- [x] I installed fresh game data from my Steam account.
- [x] I looked through the Issues section of this repository.
- [x] I looked through the Issues section of https://github.com/FWGS/xash3d repository.
- [x] I looked through the Issues section of https://github.com/FWGS/xash3d-android-project repository.

You are still here? Great! This means that you have a new bug. But this is not the end. For our mutual understanding, we require some data from you:
- [x] Short description of your problem.
- [ ] Information about your device: RAM size, CPU, GPU and OS. 
- [ ] engine.log. You can find that in your "xash" folder. If there is not log, re-run game with "-log" command line parameter. 
- [ ] adb logcat. Isn't necessary, but it will be very nice, if you can post this. You can ask Google for "How to get the "logcat" data", if you don't know what is it.

**Comment by nekonomicon** [comment]
>There's no buy weapons button in-game

Set other touch profile in **touch options** menu section.
