### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by Zu1iNMage** [FWGS/cs16-client#223]
Отсутствие моделей игроков в демке + часто бывают вылеты при попытке включить записаную демку

**Comment by a1batross** [comment]
Где логи? Где файл демки?

**Comment by Zu1iNMage** [comment]
Проверил, смотрю проблема именно при записи демо в локальной игре с ботами. На сервере модели игроков видны в демке. Логи и прочее позже

**Comment by lewa-j** [comment]
"Позже" - понятие растяжимое.
