### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by sspig1337** [FWGS/cs16-client#229]
При убийстве вместо иконки оружия неведомая хрень ))
https://yadi.sk/i/cfENurhu3EeUp5

**Comment by a1batross** [comment]
Проверь игровые файлы. Особенно папку sprites.

**Comment by sspig1337** [comment]
Поменял спрайты всё равно не работает

**Comment by lewa-j** [comment]
Проверь целостность кэша в стиме. Перекачай папку cstrike полностью.
