### ISSUE TITLE
NVG

### ISSUE THREAD

**Issue by PuGach95** [FWGS/cs16-client#231]
Доброго времени суток!
Прошу сильно не пинать, я тут новенький.
Мне кажется, что причина некореектной работы регулировки NVG кроется в некорректной записи пределов функции. А именно - [0, 30]U[220, 255].
Ваша функция
void CHudNVG::UserCmd_NVGAdjustDown()
{
	m_iAlpha = max( 220, m_iAlpha + 20 );
}

void CHudNVG::UserCmd_NVGAdjustUp()
{
	m_iAlpha = min( 30, m_iAlpha - 20 );
}
Изначально значение переменной m_iAlpha равно 110.
max присваимает переменной m_iAlpha наибольшее значение из массива.
В массиве у вас 220 и 110+20. m_iAlpha =  220
При повторнии в массиве уже оказываются значения 220 и 220+20
m_iAlpha =  240
Аналогично с функцией min
Из 30 и 110 - 20 будет выбрано 30.
При повторе 30 и 30-20
m_iAlpha =  10
Кроме того я рекомендовал бы вынести операциию присваивания за пределы max/min, оставив их только для проверки корректности введенных значений.
В окончательно варианте я предлагаю следующий код:

void CHudNVG::UserCmd_NVGAdjustDown()
{
m_iAlpha = m_iAlpha + 20;
m_iAlpha = min( 220, m_iAlpha );
}

void CHudNVG::UserCmd_NVGAdjustUp()
{
m_iAlpha = m_iAlpha - 20;
m_iAlpha = max( 30, m_iAlpha );
}

Спасибо за внимание!

**Comment by a1batross** [comment]
Да, ошибка в этом коде присутствует. Всегда выбирается либо минимум, либо
максимум. NVGAdjust ещё может неправильно работать по другой причине. Когда
команда +nvgadjust присвоена какой-то кнопке, движок при разжатии этой
кнопки автоматически вызывает парную команду: -nvgadjust. Притом, такое
поведение связано только с кнопками и именно только с командной
+nvgadjust(по аналогии с +attack, +jump и так далее).

Я конечно думаю о том, что нужны команды nvgadjustup и nvgadjustdown для
корректного их использования с кнопками.

Сейчас это можно попробовать исправить вручную: alias "nvgadjustup"
"+nvgadjust"; alias "nvgadjustdown" "-nvgadjust". Соответственно
использовать эти команды для кнопок.
27.02.2017 6:02 пользователь "Антон" <notifications@github.com> написал:

**Comment by a1batross** [comment]
Да, ошибка в этом коде присутствует. Всегда выбирается либо минимум, либо максимум. NVGAdjust ещё может неправильно работать по другой причине. Когда команда +nvgadjust присвоена какой-то кнопке, движок при разжатии этой кнопки автоматически вызывает парную команду: -nvgadjust. Притом, такое поведение связано только с кнопками и именно только с командной +nvgadjust(по аналогии с +attack, +jump и так далее). 

Я конечно думаю о том, что нужны команды nvgadjustup и nvgadjustdown для корректного их использования с кнопками. 

Сейчас это можно попробовать исправить вручную: alias "nvgadjustup" "+nvgadjust"; alias "nvgadjustdown" "-nvgadjust". Соответственно использовать эти команды для кнопок.

**Comment by a1batross** [comment]
Да, ошибка в этом коде присутствует. Всегда выбирается либо минимум, либо максимум. NVGAdjust ещё может неправильно работать по другой причине. Когда команда +nvgadjust присвоена какой-то кнопке, движок при разжатии этой кнопки автоматически вызывает парную команду: -nvgadjust. Притом, такое поведение связано только с кнопками и именно только с командной +nvgadjust(по аналогии с +attack, +jump и так далее). 

Я конечно думаю о том, что нужны команды nvgadjustup и nvgadjustdown для корректного их использования с кнопками. 

Сейчас это можно попробовать исправить вручную: alias "nvgadjustup" "+nvgadjust"; alias "nvgadjustdown" "-nvgadjust". Соответственно использовать эти команды для кнопок.

**Comment by PuGach95** [comment]
На сколько я вас понял, еще нужно изменить
	HOOK_COMMAND("+nvgadjust", NVGAdjustUp);
	HOOK_COMMAND("-nvgadjust", NVGAdjustDown);
на
	HOOK_COMMAND("nvgadjustup", NVGAdjustUp);
	HOOK_COMMAND("nvgadjustdown", NVGAdjustDown);
и внести правки в конфиги управления? Или команды все равно будут распознаваться как парные?

**Comment by a1batross** [comment]
Можно не заменять, а добавить ещё. 

Первые пусть остаются для совместимости, а вторые для адекватного управления с кнопок.

**Comment by PuGach95** [comment]
O'key, кажется все исправил.
[Uploading fix.zip…]()
