### ISSUE TITLE
Cs16-Client MinGW Compile error

### ISSUE THREAD

**Issue by ridvan1995** [FWGS/cs16-client#234]
![ekran goruntusu 32](https://cloud.githubusercontent.com/assets/11977128/23580169/16b71ae2-0105-11e7-9329-85049f011049.png)

this is what happens when i tried to compile cl_dll of cs16-client

../common/../engine/APIProxy.h:806:33: error: use of enum 'netsrc_s' without previous declaration
  void (*pfnNET_SendPacket)(enum netsrc_s sock, int length, void *data, netadr_t to); // &NET_SendPacket
                                                         ^~~~~~~~
Makefile:124: recipe for target 'cdll_int.o' failed
mingw32-make: *** [cdll_int.o] Error 1

**Comment by a1batross** [comment]
Therefore here is Makefiles, CMakeLists and so on, I don't support or plan to release CS16Client on other operating systems than Android.
