### ISSUE TITLE
хит боксы

### ISSUE THREAD

**Issue by arhangel1203** [FWGS/cs16-client#239]
Поправте пожалуйста хит боксы, пули летят не точно

**Comment by a1batross** [comment]
Версия?

**Comment by arhangel1203** [comment]
1.3 версия

**Comment by arhangel1203** [comment]
В бета тоже самое

**Comment by a1batross** [comment]
Нет, движок которой версии?

Попробуй значение ex_interp 0.01.

22 марта 2017 г. 22:03 пользователь "arhangel1203" <notifications@github.com>
написал:

**Comment by arhangel1203** [comment]
Движок 0.18.1 это значение у меня прописано в userconfig.cfg

**Comment by a1batross** [comment]
В 0.18.1 нет интерполяции, поэтому там хитбоксы соответствуют последнему ответу от сервера. 

Пробуйте бета-версию клиента и движка. Бета-версия клиента есть в Google Play, а движок в репозитории xash3d-deploy(вот [ссылка](https://github.com/FWGS/xash3d-deploy/tree/travis-latest)).

**Comment by linkowln** [comment]
Que beta é esta, a que vocês estão falando?
Podem me passar o link dela?

**Comment by a1batross** [comment]
Use English or Russian.

**Comment by arhangel1203** [comment]
Поставил ксаш бета и бета кс клиента ну что могу сказать ну вроде стало стрельба лучьше Иза упада ФПС сложно сказать и ещё вопрос разброс таким должен быть при зажими что то он сильно дергаеться?

**Comment by a1batross** [comment]
Понять бы ещё что значит сильно дёргается.

**Comment by linkowln** [comment]
эти голубые точки на cs16client сервере для чего? Это взять?

**Comment by linkowln** [comment]
Those blue balls on the cs16client server for what? How to draw?

**Comment by arhangel1203** [comment]
Так не обьясниш мог бы снять видео и посмотрел бы и понял о чем идёт речь.вк если скину в офф группу сойдёт?

**Comment by a1batross** [comment]
It's not a support desk. Don't ask your questions here.
Blue dots is an enabled debug tool. Just ignore it.
-------
Вот иди и записывай. ВК не для багов, так что как-нибудь сюда закинь.
Только в отдельную ишшую. Один баг -- одна ишшуя. И оформляй их согласно
рекомендациям, которые показываются при открытии новой ишшуи.

24 марта 2017 г. 3:45 пользователь "linkowln" <notifications@github.com>
написал:

эти голубые точки на cs16client сервере для чего? Это взять?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/FWGS/cs16-client/issues/239#issuecomment-288902273>,
or mute
the thread

**Comment by arhangel1203** [comment]
Чтож алибек все ясно, ну сам пересмотри стрельбу и отдачю и разброс.сверя с пкашной кс может сможешь поченить))))

**Comment by a1batross** [comment]
Ты так пишешь, словно я в тебе нуждаюсь. Это не так. Я нуждаюсь в грамотных
людях.
24.03.2017 11:55 пользователь "arhangel1203" <notifications@github.com>
написал:

**Comment by linkowln** [comment]
Sorry, i did not know.

**Comment by arhangel1203** [comment]
Алибек я всего-то прошу поправить стрельбу,и все увижу ещё что-то серьёзное сообщю

**Comment by a1batross** [comment]
Ну какие-нибудь есть доказательства неправильной стрельбы?

Я в первую очередь тестирую именно правильность стрельбы: разброс, хитбоксы
и тому подобное. Ты меня ещё ни разу не переубедил.

На всякий случай проверил на последней версии, всё в порядке. Единственное,
значение времени интерполяции должно быть 0.01. С 0.1 слишком большая
задержка.

**Comment by linkowln** [comment]
When will the official cs16client version 1.4 come out?

**Comment by arhangel1203** [comment]
Я общяюсь с игроками состою в клане и многие говорят что хитбоксы и стрельба кривая я думаю не только мне тут одному кажется, и сокланы тоже самое говорят вот Иза этого и я поднял тему чтоб узнать всю суть, правдо ли оно так?

**Comment by a1batross** [comment]
Ну мало ли что говорят другие люди. :) 

Так, хватит флудить. По делу есть ещё что-нибудь сказать? 
Я не могу воспроизвести с моими параметрами(ex_interp 0.01, повторяю ещё раз).

**Comment by arhangel1203** [comment]
Ок я все понял буду ждать обновы
