### ISSUE TITLE
Motion Blur

### ISSUE THREAD

**Issue by EquinoxSTR4F3** [FWGS/cs16-client#245]
Can you add motion blur to counter strike 1.6?

RUS:
Вы добавите motion blur к counter strike 1.6?

**Comment by a1batross** [comment]
OpenGL Accumulation Buffer can't be used in GLES.
FBO is not usable in Xash3D Android port(because renderer still not ported to GLES and uses GL to GLES translator).

So... while engine don't have a native GLES renderer, it's not possible or very hard and useless.
