### ISSUE TITLE
Cant play on servers

### ISSUE THREAD

**Issue by EquinoxSTR4F3** [FWGS/cs16-client#247]
Hi, dear "cs16-client" player. :)

Since developers are too busy, we don't have too much time to work with each bug of each user.

So before you will press *Submit* button, make sure you have checked all the paragraphs below:
- [ ] I installed latest versions of cs16-client and Xash3D port. (look here: https://github.com/FWGS/cs16-client/releases/latest and https://github.com/FWGS/xash3d-android-project/releases/latest)
- [ ] I installed fresh game data from my Steam account.
- [ ] I looked through the Issues section of this repository.
- [ ] I looked through the Issues section of https://github.com/FWGS/xash3d repository.
- [ ] I looked through the Issues section of https://github.com/FWGS/xash3d-android-project repository.

You are still here? Great! This means that you have a new bug. But this is not the end. For our mutual understanding, we require some data from you:
- [ ] Short description of your problem.
- [ ] Information about your device: RAM size, CPU, GPU and OS. 
- [ ] engine.log. You can find that in your "xash" folder. If there is not log, re-run game with "-log" command line parameter. 
- [ ] adb logcat. Isn't necessary, but it will be very nice, if you can post this. You can ask Google for "How to get the "logcat" data", if you don't know what is it.

I cant play on servers, my game  crashes for some reason, this started just half a week ago, i dont know why, this just started happening. Pls fix?

**Comment by a1batross** [comment]
I hope one day people will learn how to read.

**Comment by EquinoxSTR4F3** [comment]
I cant even play in single player

**Comment by a1batross** [comment]
I don't care. 

I have written the explanation(yep, it's starts from "Hi, dear player...") of good bugreport. But you ignored it. So I don't care. I don't get anything from these dumbness. 

It's your problem, solve it by yourself.
