### ISSUE TITLE
Source Code to Application

### ISSUE THREAD

**Issue by barrycade** [FWGS/cs16-client#250]
So sir this is my problem. Im a student in the philippines and I want to build the source code into apk but it have a lot of errors.
My only question is, what program should I use to build it into apk? Thankyou for your quick response.

**Comment by a1batross** [comment]
Use Android SDK and NDK(version r10e is recommeded). 

Then just run "build" script from android/ directory. 

I'm working on Linux, and never tested it on Windows, so... good luck. :)

**Comment by barrycade** [comment]
That kinda hard for me cause im a very noob. 17 years old hahaha by the way thankyou sir for your response. I just wanted to build it and add guns in it. But i cant😢 Do you have some apk there sir? That have a lot of guns can use in game?

Sent from my Sony Xperia™ smartphone

---- Alibek Omarov wrote ----

**Comment by a1batross** [comment]
No. I don't have any versions with modded guns. 

Maybe you should try add guns with AMXX or modify ReGameDLL_CS source code and run server with it?

**Comment by EquinoxSTR4F3** [comment]
will this be like a CS source game for android? if yes, im totally downloading this

**Comment by nekonomicon** [comment]
Nope.

**Comment by barrycade** [comment]
I just wanna add weapons but that is kinda hard because the source code have a lot of errors when i imported it in android studio. The source code is the only thing that I can do to make my purpose come true. Sorry for bad english.

**Comment by barrycade** [comment]
And amxx does not support in android.

**Comment by a1batross** [comment]
I don't use Android Studio. There is no so much Android-specific code to run it in bloated IDE. 

You can run AMXX on PC(Windows or Linux) and connect from Android device.

**Comment by barrycade** [comment]
Im using windows 10 right now sir. Is there anything (tutorial) that can teach me how to connect amx in android?

**Comment by a1batross** [comment]
There is no big difference in running HLDS or XashDS(Xash3D Dedicated
Server).

Just follow any tutorial to run CS1.6 server with AMX Mod X, but using
Xash3D Dedicated Server. You can download it from releases in "xash3d"
repository.

2017-05-28 12:43 GMT+03:00 barrycade <notifications@github.com>:

**Comment by barrycade** [comment]
Okay thankyou. Can you build an apk with amxx sir? Is that possible? So that i can also make a mod of zombie. Just a suggestion.

**Comment by a1batross** [comment]
At this time it's not impossible. I had started porting AMXModX on Android some time ago, but I don't have free time to continue. 

If you still want ignore the only supported way to build CS16Client from source(running buildscript), then close this issue maybe?

**Comment by barrycade** [comment]
Okay sir thankyou very much for this.

**Comment by oussama276** [comment]
@barrycade Were in 2022 I know 👀 but I came up with a solution to run some plugins in the game if you re alive 🕸️ download termux apk and watch this explainer. https://youtu.be/4ge2n5-yETo
