### ISSUE TITLE
Make Servers Gr8 Again!

### ISSUE THREAD

**Issue by EquinoxSTR4F3** [FWGS/cs16-client#251]
There were some servers that were fun but removed (hide and seek and KZ for example) and also some fun plugins that were removed as well ( AUTOHOP on csdm and pub and russian servers) will they ever be back? at least bring hns back. with the maps it had.

**Comment by nekonomicon** [comment]
We are not server owners!

**Comment by a1batross** [comment]
We need to build a wall.

Ehm. Sorry. Yes, Flying With Gauss does not offer servers nor host any. Ask server owners for that(some server administrators put their contacts in MOTD or it shows in chat sometimes).
