### ISSUE TITLE
Playing with a high resolution screen is very cumbersome, changing resolution, fov or zoom level needed

### ISSUE THREAD

**Issue by Jake762x51** [FWGS/cs16-client#259]
I use a LG G6 and no matter how i fiddle with the different settings available to me, the cross-hair is tiny and all the UI too. 

The biggest problem is that i have to get very very close to my display to see the enemy properly. 

Would it be somehow possible to be zommed in so to say all the time or lower the resolution to archive getting a closer view of the scene ?

**Comment by a1batross** [comment]
You can scale up HUD with "hud_scale N" in console, where N is scaling factor. Then you should restart the game.

**Comment by Jake762x51** [comment]
Oh thanks, but is it possible to somehow zoom or lower the resolution overall so i can see the enemy better  without having to put my eyes 5cm infront of my display ?

**Comment by a1batross** [comment]
FoV is locked, it's a CS rules, so I don't have added this.

Engine can't change resolution on Android at this time. 

You need to restart the game by Quit button, so config files will be written.

**Comment by Jake762x51** [comment]
Ah understood,
Thats really unfortunate.
If you have any workaround or trick to archieve the zoom im looking for, please tell me !

Thanks for everything

**Comment by a1batross** [comment]
You can use Android Resolution Changer, but this way isn't really good,
because it changes resolution over all applications and of course requires
root. :(

2017-07-01 14:43 GMT+03:00 Jake762x51 <notifications@github.com>:

**Comment by Jake762x51** [comment]
Thank you so much for taking the time to reply and trying to think of ways to solve this problem, you are an awesome dev, i am sure you will  find a way, one day, to solve this problem too ;)
Spasiba bratan.
