### ISSUE TITLE
Не могу собрать Client.dll в VS 2013

### ISSUE THREAD

**Issue by porloc** [FWGS/cs16-client#261]
Здарова чуваки,
Я новичок в этом, помогите плиз. Проект скомпилировался, но при линковке он ругается на разные функции из модуля pm_math.cpp. Например:

1>rain.obj : error LNK2019: ссылка на неразрешенный внешний символ "void __cdecl VectorTransform(float *,float (*)[4],float *)" (?VectorTransform@@YAXPAMPAY03M0@Z) в функции "void __cdecl SetPoint(float,float,float,float (*)[4])" (?SetPoint@@YAXMMMPAY03M@Z)

Проверил заголовки в pm_math.obj через утилиту DUMPBIN. А там вот что:

 ?VectorTransform@@YAXQBMQAY03MQAM@Z (void __cdecl VectorTransform(float const * const,float (* const)[4],float * const))

Несовпадают параметры и decorated name. И так во всех функциях на которые он ругается, компилятор почему то суёт лишние const.

Сам модуль с header'ом соответствует. Свойства модуля проверил вроде всё по дефолту, никаких оптимизаций не включено. Проект сгенерировал через CMake. Логи не смог приложить, github не принимает файлы.

Вот еще несколько примеров:
Linker:
1>view.obj : error LNK2019: ссылка на неразрешенный внешний символ "void __cdecl NormalizeAngles(float *)" (?NormalizeAngles@@YAXPAM@Z) в функции "void __cdecl V_SmoothInterpolateAngles(float *,float *,float *,float)" (?V_SmoothInterpolateAngles@@YAXPAM00M@Z)
DUMPBIN:
?NormalizeAngles@@YAXQAM@Z (void __cdecl NormalizeAngles(float * const))

LINKER:
1>pm_shared.obj : error LNK2019: ссылка на неразрешенный внешний символ "void __cdecl CrossProduct(float const * const,float const * const,float * const)" (?CrossProduct@@YAXQBM0QAM@Z) в функции "int __cdecl PM_FlyMove(void)" (?PM_FlyMove@@YAHXZ)
DUMPBIN:
?_CrossProduct@@YAXPBM0PAM@Z (void __cdecl _CrossProduct(float const *,float const *,float *))

**Comment by porloc** [comment]
Исходники взял из релиза 1.32

**Comment by a1batross** [comment]
MSVC не поддерживается, как и Windows-сборки.
