### ISSUE TITLE
Xash3d Masterserver is screwed

### ISSUE THREAD

**Issue by ridvan1995** [FWGS/cs16-client#265]
Hi. On yesterday i noticed that my servers not showing up in serverlist. I pinged masterserver address(ms.xash.su & ms.fwgs.ru) in my 2 Vps (their locations are germany and italy) and they showed that host is down. To make sure i check all of the server's location and i found no west countries only asia and middle east. Is something wrong with the masterserver?

![ekran goruntusu 82](https://user-images.githubusercontent.com/11977128/30132687-ea0e712e-9359-11e7-9adc-b618981d8bda.png)

**Comment by a1batross** [comment]
@jeefo

**Comment by fuzun** [comment]
traceroute yapıp çıktıyı at.

**Comment by ramazan5134** [comment]
Please help ridvan

**Comment by ramazan5134** [comment]
root@cs:~# traceroute
The program 'traceroute' can be found in the following packages:
 * inetutils-traceroute
 * traceroute
Try: apt install <selected package>
root@cs:~#
Bu cikiyor

**Comment by ridvan1995** [comment]
@fuzun 
![ekran goruntusu 83](https://user-images.githubusercontent.com/11977128/30203158-da16e84c-9489-11e7-9202-5e5e495d7c6f.png)

**Comment by ramazan5134** [comment]
@fuzun

**Comment by ramazan5134** [comment]
@fuzun

**Comment by jeefo** [comment]
Provide IP addresses.

**Comment by ridvan1995** [comment]
@jeefo 
left one(root@Xdxd): 80.211.128.217
right one(root@cs): 138.197.179.108 (that one closed)

**Comment by ramazan5134** [comment]
@jeefo

**Comment by jeefo** [comment]
Will look into

**Comment by ridvan1995** [comment]
@jeefo Any progress?
