### ISSUE TITLE
Other errors ingame CS16client apr12017

### ISSUE THREAD

**Issue by gr01d** [FWGS/cs16-client#266]
Hi, dear "cs16-client" player. :)

Since developers are too busy, we don't have too much time to work with each bug of each user.

So before you will press *Submit* button, make sure you have checked all the paragraphs below:
- [ ] I installed latest versions of cs16-client and Xash3D port. (look here: https://github.com/FWGS/cs16-client/releases/latest and https://github.com/FWGS/xash3d-android-project/releases/latest)
- [X] I installed fresh game data from my Steam account.
- [X] I looked through the Issues section of this repository. ENGLISH only
- [X] I looked through the Issues section of https://github.com/FWGS/xash3d repository. outdated
- [X] I looked through the Issues section of https://github.com/FWGS/xash3d-android-project repository. notmuchinfo

You are still here? Great! This means that you have a new bug. But this is not the end. For our mutual understanding, we require some data from you:
- [ ] Short description of your problem.
- [ ] Information about your device: RAM size, CPU, GPU and OS. 
- [ ] engine.log. You can find that in your "xash" folder. If there is not log, re-run game with "-log" command line parameter. 
- [ ] adb logcat. Isn't necessary, but it will be very nice, if you can post this. You can ask Google for "How to get the "logcat" data", if you don't know what is it.

Whenever you shoot, after just shooting someone or something the guns muzzleflash flashes again after seconds in initial shooting. The bots appear to be randomly roaming around and not defusing bombs and using the radio says "I'm gonna camp" indefinitely until someone interrupt or answer him. 

Xash3DS for CS16Client does not have version for Raspberry pi (debian + raspberry pi = raspbian stretch 9.1 ARMHF) it would be helpful to run a local or internet server on a raspberry pi (arm SBC Power consumption 10watts) than a ATX 700W PC.

**Comment by a1batross** [comment]
I know about muzzleflash bug, it's a predicting bug in engine. 


I'm not interested in client for other platforms other than mobile. BTW, you can run a Xash Dedicated Server and compile ReGameDLL_CS for ARM.

**Comment by gr01d** [comment]
thanks for your reply, this issue will now be closed
