### ISSUE TITLE
just a question to devs

### ISSUE THREAD

**Issue by kuwoh** [FWGS/cs16-client#268]
Why is cs16-client close sourced now? very curious about it

**Comment by nekonomicon** [comment]
One guy from testers wrote and published cheats for cs16client.

**Comment by a1batross** [comment]
He was not from testers. 

BTW, source is closed because I plan to do many things for securing normal players from nasty cheaters. 

If you want to copy something from cs16-client or use it for your base mod, I have left legacy source code here.

**Comment by kuwoh** [comment]
uh one more thing, will you guys do a pc build of cs16-client? but add a server cvar whether to allow mouse/pc users?

**Comment by a1batross** [comment]
Maybe. 

Engine itself have "sv_allow_mouse", "sv_allow_touch" and so on, but it's not secured from self-compiled engine.

**Comment by kuwoh** [comment]
i'll be looking forward for the pc version :D

**Comment by kvdrrrrr** [comment]
security through obscurity is a bad, lazy workaround to the problem.

**Comment by a1batross** [comment]
@kvdrrrrr it's not a security. Security is about protecting personal information. And this is just a game, nothing serious.

Or... you can suggest any open source solution against cheaters?

**Comment by kvdrrrrr** [comment]
if i recall correctly osu! is an open source project, but some parts of it (namely anti-tamper and anti-cheating solutions) are kept private. official servers won't allow you to connect with a custom build, because of missing stuff. and there's multi theft auto which is open-sourced as well and also deals with cheaters somehow.

**Comment by a1batross** [comment]
Osu! at this time is closed-source. New client is free&open, but it's not released, as in too early stages of development.

CS16Client is stays partially open-source. You still can download the legacy source code and use it in your mod for free(and even re-license, as I don't care about old code) or just play locally.
What's the purpose to keep more "online game" ready client open source? Even if I will implement AC in standalone module and keep client open, you will still run the closed-source AC module and who knows what's inside?

**Comment by a1batross** [comment]
@kuwoh 
So... what can I do with evil players,

**Comment by kuwoh** [comment]
check server side checking aswell if client doesn't respond with correct packet that has a generated codes of cvar if any errors exist kick player (just a suggestion tbh not really forcing things in just for open sourcing)

**Comment by a1batross** [comment]
There is many AMXModX-based serverside anticheats, that works same way.

**Comment by kuwoh** [comment]
hmm what kind of cheats were developed? for cs16-client anyways? wallhack? aimbot?

**Comment by a1batross** [comment]
Let's think from the practical side of the question. Why someone will modify client at all? 
1) To develop their game modification.
2) To develop cheats. 

The first one is still possible with the legacy source code from 1.33 version. The second one isn't interesting for me. 

I don't see any reasons to keep updates open source.

**Comment by ridvan1995** [comment]
pc version on ubuntu is possible and works great. but windows.. doesnt even compile

**Comment by a1batross** [comment]
I personally don't want PC users on a _mobile_ game. Using legacy source
code to play from PC, not develop or admin servers, is a dick move to
players.

3 янв. 2018 г. 7:50 ПП пользователь "Rıdvan Nurican Topal" <
notifications@github.com> написал:
