### ISSUE TITLE
Why closed source?

### ISSUE THREAD

**Issue by gr01d** [FWGS/cs16-client#270]
Why did you closed source the development of  cs16client? Are you planning to sell it?
Will the xash3d android project be still open source?

**Comment by nekonomicon** [comment]
>Why did you closed source the development of cs16client?

https://github.com/FWGS/cs16-client/issues/268#issuecomment-342682015

>Are you planning to sell it?

You can't sell games under Valve EULA(HLSDK License).

>Will the xash3d android project be still open source?

Sure.

**Comment by a1batross** [comment]
@nekonomicon thanks for answering here. :)
