### ISSUE TITLE
Frequent crashes in the latest version

### ISSUE THREAD

**Issue by leopard20** [FWGS/cs16-client#274]
The game crashes in less than 1 minute of playing in the latest version, regardless of xash3d version.

I tested v1.2 of the client and it works really well, so something is probably broken.

**Comment by leopard20** [comment]
My device specs:
Android 7.0
Chipset: Snapdragon 821

**Comment by nekonomicon** [comment]
Turn off zbot. Play with yapb.
Or download latest test version of xash3d fwgs from xash3d-deploy repo.

**Comment by leopard20** [comment]
Like I said it happens **regardless of Xash3D version**.

**Comment by a1batross** [comment]
logcat

23 февр. 2018 г. 21:20 пользователь "Leo" <notifications@github.com>
написал:

**Comment by leopard20** [comment]
I don't know what happened, but it works fine now.
