### ISSUE TITLE
Нельзя играть с игроками с PC версией CS 1.6?

### ISSUE THREAD

**Issue by Karaulov** [FWGS/cs16-client#280]
Нельзя играть с игроками с PC версией CS 1.6? Если нельзя то будет ли это исправлено в будущем?

**Comment by nekonomicon** [comment]
1. Оригинальный клиент CS 1.6 не работает под PC-версией Xash3D, потому что использует недокументированые особенности GoldSource.
2. Xash3D и GoldSource используют разные сетевые протоколы, которые не совместимы между собой и маловероятно, что будет какая-то совместимость в будущем.
3. Релизы CS16Client для пк пока не планируются.

**Comment by Karaulov** [comment]
А создатель эмулятора steam если захочет сможет сделать поддержку CS16Client ?

**Comment by a1batross** [comment]
Бред. Нет. 
Порт на ПК неизвестно ещё будет или нет.

**Comment by Karaulov** [comment]
Владельцев ПК больше играют в игры типа CS , сделайте порт если это возможно :(

**Comment by mittorn** [comment]
Karaulov, для ПК есть оригинальная cs 1.6, так что именно для ПК с windows порт нужен разве что для локальной игры с тач-устройствами. На серверах это вызовет скорее проблемы
Другое дело что есть планшеты на windows и порт на них был бы очень полезен - там windows и android игроки на равных будут. Ещё есть всякие freebsd и другие ОС, для которых нет нативных версий кс

**Comment by Karaulov** [comment]
Да нет я имел ввиду именно PC, если качество будет такое же то никому разницы не будет в какую играть, в настоящую 1.6 или этот порт)  Больше игроков 
Да и всяких тупых модов не будет, а то заходишь на сервер и не известно что тебя там ждет, то варкрафты то еще что))))

**Comment by mittorn** [comment]
Наоборот будут всякие тупые моды. Зайдёшь на сервер, а там майнкрафт какой-нибудь с зомбимодом
