### ISSUE TITLE
Не получает доступ к SD карте

### ISSUE THREAD

**Issue by Karaulov** [FWGS/cs16-client#281]
Пишет что нет доступа к карте памяти, и даже не пытается получить доступ. Можете исправить это что бы полноценно устанавливать на карту памяти папку xash ?

**Comment by a1batross** [comment]
RoDir.

**Comment by Karaulov** [comment]
Не  понял ничего, все приложения запрашивают доступ, типа выберите карту памяти в списке, после чего получают полный доступ. А эта не хочет, жму ОК и перестает работать.

**Comment by nekonomicon** [comment]
Все приложения написаные целиком на java, либо работающие только на Android 5.0+(при этом использующие нововведения для доступа к фс)получают полный доступ. Это так.
Есть еще туториал в последней версии xash3d fwgs, рекомендую ознакомится, если пропустили.
RoDir указывается там же.

**Comment by a1batross** [comment]
Значит надо обновить движок. Последняя версия автоматом предлагает воспользоваться RoDir на ФС только для чтения.
