### ISSUE TITLE
Не регулируется звук никакими существующими способами.

### ISSUE THREAD

**Issue by Karaulov** [FWGS/cs16-client#283]
Команду volume писал, уменьшал в настройках до 0 звук, перед запуском делал тише звук в телефоне, во время игры нажимал Volume- кнопку, никакой реакции.

В главном меню ревет на полной громкости, у меня телефон даже на максимуме такого звука не выдает в плеере, как в меню CS 1.6..... ))))))

Надо исправить как-то, подскажите)))))

**Comment by a1batross** [comment]
В 1.4.

**Comment by Karaulov** [comment]
а сейчас какая ? 0.3 ?)))

**Comment by a1batross** [comment]
Что за беззащитность? Посмотри сам.
