### ISSUE TITLE
Cross Platform Multiplayer (LAN) is not working

### ISSUE THREAD

**Issue by ahmedadel2214** [FWGS/cs16-client#288]
When I start a game on a PC , it does not show on the android game app , and when trying to use the command 'connect <IP>' it does not connect it does nothing . I tried to do the opposite and create a game from the android and try to connect on the PC same issue happens.
Knowing that both PC and android has the same CS1.6 files (copied the android files from this version on PC) .
*Tried :-*
- Other Devices (android / PC)
- Other Game Versions
- Other installations

Knowing That The Devices Can Play Multiplayer Games With Their Own Types Perfectly.

**Comment by nekonomicon** [comment]
1. Original CS 1.6 client does not work under Xash3D.
2. Xash3D and GoldSource has incompatible network protocols.

>Knowing that both PC and android has the same CS1.6 files (copied the android files from this version on PC) .

What do you mean?

**Comment by a1batross** [comment]
CS1.6 on PC through Xash3D is not support and will not be in near future.
