### ISSUE TITLE
CS 1.6 hostages AI doesn't seem to work? Don't know if it's an engine-related problem or not.

### ISSUE THREAD

**Issue by sledgehammer0019** [FWGS/cs16-client#296]
I don't really know if it's an engine issue (or not). In CSMoE (created by Moe) mod (in Android) the hostages functions like the one in CSCZ were they shout for you, and they react when you bump them or shoot near them. I downloaded a CSCZ Hostage AI mod for CS 1.6 and I installed it in the directory but nothing happens, except that you can call the hostages even in far directions. I just hope that hostages might function because it adds realism to the game! Thank you! 
3GB RAM
Android 6.0.1
Mali T-720

**Comment by a1batross** [comment]
Answered in FWGS/xash3d#442 already.
