### ISSUE TITLE
Needed features In 1.4 update...

### ISSUE THREAD

**Issue by Left4Dad** [FWGS/cs16-client#300]
Hello :)

In one of my previous issues, i mentioned that you should remove the scoreboard after death. And you said you will do it. I hope you add a command for it so that we can enable or disable the scoreboard to pop up after death. Because its sometimes really annoying to look at the scoreboard.

Second, For example, when we shoot a metal, it produce metal sounds. If we walk on metal, it must produce sounds (works on PC version). In mobile version, when we shoot the metal, it does not produce metal sounds and when we walk on metal, it produces normal walking sounds instead of metal sounds.We can only hear metal sounds when other players walked on it. But when we walk, the metal sounds was not produced. I believe every mobile 1.6 players encountered this problem. Also when a player reloads, the reload generic sound should be produced just like in the pc version of cs 1.6. So mobile really need to fix these things. Hope you do something about this.

Third, is it possible to make players [throw a grenade, reload , use the knife strong attack] while defusing the bomb? This idea should be implemented. Cuz we will mostly die while defusing. Because we cant do anything. So plz consider this :D

**Comment by Left4Dad** [comment]
Another problem which is extremly annoying for android cs 1.6 gamers. The sounds in game has a bug. For example, if i use radio command "go go go" and if other people use other radio commands at the same time, it will cut off the "go go go" sounds. Plz make the sound be able to mix together like older versions. This sound bug has to be fixed. Sometimes if we did not notice the "bomb planted" word, we will not know if the bomb is planted because sometimes even the sound bomb has been planted were cutted by other produced sounds like (fire in the hole) or drawing a weapon and etc. I think this sound problem appears only on the latest Xash app. Plz fix 🙏. My friends are looking forward for fixing these issues and the ones i mentioned above. Thank You :)

**Comment by a1batross** [comment]
We don't care about GitHub issue limits, so, please, follow the main rule of reporting bugs or requesting features: **one** bug -- **one** issue.

**Comment by a1batross** [comment]
And don't forgot to look if you someone is reported bug **before you**. I remember, those sound issues were reported countless times here.
