### ISSUE TITLE
How to remove the word BOT on scoreboard?

### ISSUE THREAD

**Issue by Left4Dad** [FWGS/cs16-client#308]
In previous version of 1.6, the word Bot is not shown on the scoreboard when playing against bots which is cool. Now the BOT word will always be on the scoreboard. Is there anyways or any cmds that can remove that word from the scoreboard? Or can you make a new cmd to enable or disable the word "bot" on scoreboard for the next update?

**Comment by a1batross** [comment]
No. It's intentionally was put here, as you can't measure latency of bots.
