### ISSUE TITLE
How to let other playes use commands on Lan servers?

### ISSUE THREAD

**Issue by Left4Dad** [FWGS/cs16-client#309]
Hello, last time i created a lan server so that my friends could join me in my server. And I can use cmds like sv_gravity and others. But my friends cant use the cmds. Is there anyways to let me and my friends use the cmds? Is there someway to do it?

**Comment by a1batross** [comment]
rcon.

**Comment by Left4Dad** [comment]
Ok gonna try it later. Thx for ur answer. Can u reply my other requested features / needed to be fixed things for 1.4 update?
