### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by SuperRock2099** [FWGS/cs16-client#312]
may i ask you a question?
which IDE did you use to compile this source code to apk?

**Comment by nekonomicon** [comment]
Neither. We are not use IDE for compilation.
Just read (build)[https://github.com/FWGS/cs16-client/blob/v1.32/android/build] script.

**Comment by SuperRock2099** [comment]
Thank you，but where is it？

**Comment by nekonomicon** [comment]
In android folder.

**Comment by SuperRock2099** [comment]
Well,I want to add an inspect animation to the weapon(use "E"), but it didn't work.
Can you tell me what's wrong with this source code?Thanks.

void CGLOCK18::ItemPostFrame()
{
	if (m_pPlayer->pev->button & IN_USE)
	{
		SendWeaponAnim(GLOCK18_INSPECT, UseDecrement() != FALSE);
		m_flTimeWeaponIdle = UTIL_WeaponTimeBase() + 20;
		m_pPlayer->pev->button &= ~IN_USE;
	}
	return CBasePlayerWeapon::ItemPostFrame();
}

**Comment by nekonomicon** [comment]
On server side?

**Comment by SuperRock2099** [comment]
I use source code 1.31

**Comment by SuperRock2099** [comment]
I just  want to run it offline.QAQ

**Comment by nekonomicon** [comment]
Check 3rdparty folder, you need to edit regamelite or regamedll source code from upstream.

**Comment by SuperRock2099** [comment]
I have download two folder from https://github.com/thomaseichhorn/cs16-client/tree/master/3rdparty yesterday,what should I do now?

**Comment by nekonomicon** [comment]
But why?
Legacy CS 1.6 client source code in v1.32 branch.
You must to do:
```
git clone https://github.com/FWGS/cs16-client
cd  cs16-client
git checkout v1.32
git submodule update --init --recursive
```

If you want to change game logic you need to edit regamedll source code:
https://github.com/FWGS/regamelite
https://github.com/s1lentq/ReGameDLL_CS

**Comment by SuperRock2099** [comment]
It was so strange when I add the source code below,bro.
When I press button "E",the model just play the first frame of INSPECT animation,why?
How can it play the whole animation when I press "E"?

void CGLOCK18::ItemPostFrame()
{
if (m_pPlayer->pev->button & IN_USE)
{
SendWeaponAnim(GLOCK18_INSPECT, UseDecrement() != FALSE);
m_flTimeWeaponIdle = UTIL_WeaponTimeBase() + 20;
m_pPlayer->pev->button &= ~IN_USE;
}
return CBasePlayerWeapon::ItemPostFrame();
}

**Comment by SuperRock2099** [comment]
I've just added it to the 3rdparty folder,but it still didn't work.

**Comment by SuperRock2099** [comment]
HELLO?

**Comment by SuperRock2099** [comment]
I have edited regamelite folder in the source code , what should I do next?

**Comment by a1batross** [comment]
Guys.

We don't provide any support for any part of CS16Client source code, since it's closed.
