### ISSUE TITLE
android application crash than start de_rats6_v1 map

### ISSUE THREAD

**Issue by AndrewOculus** [FWGS/cs16-client#314]
Hello! I have a bug than i load de_rats6_v1 map (https://www.17buddies.rocks/17b2/View/Map/12450/de_rats6_v1.html). It is very beautiful
 and lovely map, I would like to use this on my server. So it crash on android device with this message:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/polaris/polaris:8.0.0/OPR1.170623.032/V9.5.19.0.ODGMIFA:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 32131, tid: 32168, name: EngineThread »> in.celest.xash3d.hl «<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40aad3
r0 0040aad3 r1 d0cfeb08 r2 0040aad7 r3 0040aadf
r4 0040aae3 r5 cf64ade4 r6 cf64add8 r7 d4f3db0c
r8 d4e89f74 r9 d0cfef60 sl d155edd4 fp d155edf8
ip c5568000 sp d0cfef30 lr cf5dcb21 pc cf5dccfc cpsr 200f0030

backtrace:
#00 pc 00046cfc /data/app/in.celest.xash3d.cs16client-L-F9IhNLmVSF3H-FJTaklw==/lib/arm/libclient_hardfp.so (CHudSpectator::SetSpectatorStartPosition()+47).

So I understand that happened in CHudSpectator::SetSpectatorStartPosition method, and I see code and find what engine search in bsp file label "trigger_camera" and other json-like labels ( "info_player_start" , "info_player_deathmatch"). So I see hex code in bsp file and find what it have normal value camera origin and angles. So I really don't understand why it crash, please help.

**Comment by a1batross** [comment]
Can't say why it crashes there. 
Need to download this map and check it on my device.

**Comment by AndrewOculus** [comment]
this archive contains map and resources
[de_rats6_v1.zip](https://github.com/FWGS/cs16-client/files/4329506/de_rats6_v1.zip)

**Comment by AndrewOculus** [comment]
Hello! so is it possible to fix it?

**Comment by AndrewOculus** [comment]
> Can't say why it crashes there.
> Need to download this map and check it on my device.

Hello! so is it possible to fix it?

**Comment by AndrewOculus** [comment]
Solved!
