### ISSUE TITLE
The server cannot appear on the list

### ISSUE THREAD

**Issue by HatsuneMiko** [FWGS/cs16-client#316]
Hello, my xashds server is in China, I added public 1 in server.cfg, but I still can't display it in the server list.

**Comment by HatsuneMiko** [comment]
I found the reason because of the port mapping I used.
Is there a way to get portmapped servers to appear on the list?

**Comment by mittorn** [comment]
when port mapped correctly, router rewrites outgoing port of packet to external mapping port, so master will get correct external port from incoming udp packet and use it in server list. If something wrong, check if NAT/mapping working correctly.
