### ISSUE TITLE
Не получается запустить андройд билд, помогите

### ISSUE THREAD

**Issue by AndrewOculus** [FWGS/cs16-client#318]
Попробовал сделать билд самостоятельно, для того чтобы лучше понять как кастомизировать игру. Использовал ndk r10e. Временно (именно временно, потому что иначе не получалось собрать) выпилил рекламу для дебага, потому что сборщик требовал старый ad плагин. Собрал с помощью ant apk-файл и запустил на телефоне, однако при нажатии на кнопку старт в ui-thread что то происходит, тк он чуть чуть начинает притормаживать, но игра не запускается. Подскажите пожалуйста что это может быть? Логи прилагаю.
[log.txt](https://github.com/FWGS/cs16-client/files/4703354/log.txt)

**Comment by a1batross** [comment]
Поддержка по существующему исходному коду не осуществляется.

Вы сами по себе.
