### ISSUE TITLE
Cyrillic letters

### ISSUE THREAD

**Issue by Czarintax** [FWGS/cs16-client#319]
Why I can't see Cyrillic letters on online servers? Is there anything i can do to be able to see it? 

![Screenshot_20200610-205951_Xash3D FWGS](https://user-images.githubusercontent.com/38297231/84597986-29dad980-ae70-11ea-8300-655585e25f97.jpg)

- [✔] I installed latest versions of cs16-client and Xash3D port.
- [✔] I installed fresh game data from my Steam account.
- [✔] I looked through the Issues section of this repository.
- [✔] I looked through the Issues section of https://github.com/FWGS/xash3d repository.
- [✔] I looked through the Issues section of https://github.com/FWGS/xash3d-android-project repository.

**Comment by lewa-j** [comment]
hud_utf8 1 in console
