### ISSUE TITLE
Playing Xash3D CS1.6 Servers in PC

### ISSUE THREAD

**Issue by PedroxTheBest99** [FWGS/cs16-client#320]
Hello,

I'm trying to run some CS 1.6 Xash3D Servers into PC but for some reason it says there is an password

https://prnt.sc/tseo9w
https://prnt.sc/tsepbw

So, if there is an password for the game into Xash3D's code, what is it?

**Comment by a1batross** [comment]
It's impossible due to completely different protocols.
