### ISSUE TITLE
How to view your own xashid on the client？

### ISSUE THREAD

**Issue by HatsuneMiko** [FWGS/cs16-client#321]
How to view your own xashid on the client？

**Comment by mittorn** [comment]
Only server can view xash id for now

**Comment by lewa-j** [comment]
There is no need for this.

**Comment by berke33110** [comment]
You can add a custom cvar to the engine(NOT xash3d-hlsdk OR cs16-client, clone FWGS/xash3d REPO FOR ENGINE) that reads and prints the ID_GetMD5() from common/identification.c
