### ISSUE TITLE
Keyboard buying still doesn't work

### ISSUE THREAD

**Issue by W1nKille3r** [FWGS/cs16-client#333]
Latest update - disable any touch support.
Using evdev commands.
With old menu style.
And he load touch cfg. WHY
How to block that??? After closing on 0 he still opening touch cfg. I can't find path where that stored.
1,2,3,4,5,6,7,8,9,0
All blocking touch UI

Like... D@faq, use touch UI even after using evdev commands + disabled touch support on OLD STYLE MENU. Im pissed off.

**Comment by a1batross** [comment]
¯\_(ツ)_/¯

**Comment by W1nKille3r** [comment]
> `¯\_(ツ)_/¯`

Very funny, how touch disable exec. Or delete that? If i try type buying manualy in console - he still execing numbericallmenu.cfg.

Like its alias or what kind of that. So Buying command is modified.

**Comment by a1batross** [comment]
Honestly, I don't remember.

**Comment by W1nKille3r** [comment]
> 

I managed how to disable that with setinfo _vgui_menus 0 & gui_menus 1

But after restarting xash3d its doesn't work anymore

**Comment by W1nKille3r** [comment]
Config.cfg being edited, and he delete gui_menus command. Even using cfg file for rebinding it - still doesn't work

**Comment by W1nKille3r** [comment]
Maybe if i try to disable to edit config.cfg. Maybe he will off to exec it.

**Comment by W1nKille3r** [comment]
> 

Nah.. No effect.
But i found a new one.
Touch folder have all exec file - if i delete it, its will stop exec that mess.
But i can't found it. Touch.cfg doesn't exist too. Root Explorer doesn't find any hidden files

**Comment by mittorn** [comment]
All additional configs are in extras.pak. You can override it by creating empty files instead.
You can even write keyboard-based menu on config logic (use bind and aliases to keep current menu state and touch buttons to draw it on screen)

**Comment by W1nKille3r** [comment]
> All additional configs are in extras.pak. You can override it by creating empty files instead. You can even write keyboard-based menu on config logic (use bind and aliases to keep current menu state and touch buttons to draw it on screen)

FOUND SOLUTION

extras.pak doesn't exist and making blanck file don't effect anything.

BUT

If you make copy on xash3D folder.
Like execution make a path: touch/useless_sh1t.cfg

With cfg's. That will be use them to exec. So - he read exist file in cstrike/touch/cfg.cfg
And make an error.

Proem solved. But anyways how that mfk exec NON-EXISTANCE file? Like cmon managed, you can't be serious. Make an cfg folder on apk.

**Comment by W1nKille3r** [comment]
Proem solved
