### ISSUE TITLE
Mouse can't rotate 360 in some phones

### ISSUE THREAD

**Issue by Ray144p** [FWGS/cs16-client#334]
So, i'm trying to play cs1.6 with my mouse & keyboard. But after i disable ignore mouse and play, the mouse won't rotate 360. But the others are fine.

Device : Redmi 9C
Spec =
RAM : 4GB
OS : Android 10, MIUI 12
Chipset : MediaTek MT6765G Helio G35 (12 nm)
CPU : Octa-core (4x2.3 GHz Cortex-A53 & 4x1.8 GHz Cortex-A53)
GPU : PowerVR GE8320

**Comment by a1batross** [comment]
Not supported.
