### ISSUE TITLE
Mouse issues with the latest version of cs16client on the googleplay store

### ISSUE THREAD

**Issue by abubakar179** [FWGS/cs16-client#338]
"Describe your problem with keyboard. 

Using mouse is prohibited in CS16Client.

_Originally posted by @a1batross in https://github.com/FWGS/cs16-client/issues/252#issuecomment-304791750_"

I've granted xash root perms and i've re enabled mouse in controls. looking around doesnt work and once a keyboard and mouse is connected once you join a server its tricky choosing t or ct, you have to press it quite a bit with your mouse and finger and just hope it works. the mouse only looks around if you drag. why did you prohibit using mouse anyways?

**Comment by abubakar179** [comment]
i dont get why this has been implemented, especially considering this app is closed source, and i need to give root access just so i can get "full support" for keyboard and mouse. plus, using keyboard and mouse isn't cheating, that's how you play it on desktop. things don't add up.

**Comment by a1batross** [comment]
I don't care.
